name: ${PROJECT_NAME}
services:
  develop:
    build: 
      context: .
      dockerfile: ./docker/dev/app.Dockerfile
    volumes:
      - ".:/develop"
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:17
    env_file:
      - ./.env
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: {}
