name: ${PROJECT_NAME}
services:

  develop:
    build: 
      context: .
      dockerfile: ./docker/dev/app.Dockerfile
    volumes:
      - ".:/code"
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:17
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data

  tailwind:
    build: 
      context: .
      dockerfile: ./docker/dev/tailwind.Dockerfile
    volumes:
      - ".:/code"
    tty: true

volumes:
  database-data: {}
