services:
  develop:
    build: .
    volumes:
      - ".:/develop"
    env_file:
      - ./src/.env
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:17
    env_file:
      - ./src/.env
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: {}
